In [1]:
import pandas as pd
import numpy as np

In [7]:
data = {
    "supplier": ["A", "B", "C" , "B", "A"],
    "LEAD_TIME": [5, 10, 15, 20, 25],
    "QUANTITY": [100, 200, 300, 400, 500],
}
df = pd.DataFrame(data)
df

  supplier  LEAD_TIME  QUANTITY
0        A          5       100
1        B         10       200
2        C         15       300
3        B         20       400
4        A         25       500

In [24]:
df

  supplier  LEAD_TIME  QUANTITY
0        A          5       100
1        B         10       200
2        C         15       300
3        B         20       400
4        A         25       500

In [25]:
df["LEAD_TIME"]

0     5
1    10
2    15
3    20
4    25
Name: LEAD_TIME, dtype: int64

In [26]:
df["LEAD_TIME"].mean()

np.float64(15.0)

In [27]:
df["QUANTITY"].sum()

np.int64(1500)